# Generated by Django 4.1 on 2022-09-03 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128, verbose_name='Автор')),
                ('name', models.CharField(max_length=128, verbose_name='Название книги')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('management', models.PositiveIntegerField(verbose_name='Номер коробки, где лежит книга')),
                ('from_made_in', models.CharField(blank=True, max_length=64, null=True, verbose_name='Место издательство')),
                ('made_in', models.CharField(blank=True, max_length=64, null=True, verbose_name='Издательство')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сколько страниц?')),
                ('status', models.CharField(blank=True, max_length=32, null=True, verbose_name='Состояние книги')),
                ('date_active', models.DateField(blank=True, null=True, verbose_name='День рекламы')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Книгу',
                'verbose_name_plural': 'Книги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChapterBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название жанра')),
                ('tag_alib', models.CharField(max_length=128, verbose_name='Тег алиба')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка книги')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books', verbose_name='Книга')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.chapterbooks', verbose_name='Жанр'),
        ),
    ]
