# Generated by Django 4.1 on 2022-09-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ['book'], 'verbose_name': 'Фотографию книги', 'verbose_name_plural': 'Фотографии книг'},
        ),
    ]
